trigger:
- Github-Actions

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: Bash@3
  displayName: 'Check for IPs'
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash

      # Function to check files for IP addresses
      scan_file_for_ips() {
          ip_addresses=$(grep -E -o "\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b" "$1")
          echo "$ip_addresses"
      }

      # Function to check the repos for IP addresses
      scan_repository_for_ips() {
          local ip_addresses=""
          
          # Loop over all files in the current dir and its subdir
          while IFS= read -r -d '' file; do
              ip_addresses+=$(scan_file_for_ips "$file")
          done < <(find . -type f -print0)
          
          echo "$ip_addresses"
      }

      # Main function
      main() {
          ip_addresses=$(scan_repository_for_ips)

          if [ -n "$ip_addresses" ]; then
              echo "IP addresses found in the repository:"
              echo "$ip_addresses"
          else
              echo "No IP addresses found in the repository."
          fi
      }

      # Run the main function
      main
